[workspace]
name = "intimate-note"
id = "note"
title = "Intimate Note Sample"
version = "0.1.0"
[publish]
publisher_dir = "../../"

[urn]
path_schema = ["chapter"]
hierarchy = ["number"]
bit_layout = [16]

[build.default]
