[workspace]
name = "Intimate Note Sample"
version = "0.1.0"
source = "https://www.it.iitb.ac.in/~sri/ssrvm/knowledge.htm"
path_schema = []

[urn]
publisher = "intimate.org"
corpus = "note"
hierarchy = ["number"]

[build]
publication = "ssrvm.org:intimate-note:default"
layout = "sequence"
templates = ["html"]
target = "view"
output = "intimate-note.vyview"
