[workspace]
name = "intimate-note"
id = "intimate-note"
title = "Intimate Note Sample"
version = "0.1.0"
[publish]
publisher_dir = "../../"

[urn]
hierarchy = ["number"]
bit_layout = [16]

[build.default]
layout = "document"
target = "view"
