[workspace]
name = "minimal"
title = "Minimal Sample"
version = "0.1.0"
[publish]
publisher_dir = "../../"

[urn]
path_schema = ["chapter"]
corpus = "min"
hierarchy = ["chapter"]
bit_layout = [16]

[build.default]
layout = "document"
target = "view"
