[workspace]
name = "Minimal Sample"
version = "0.1.0"
path_schema = []

[urn]
publisher = "minimal.org"
corpus = "min"
hierarchy = ["chapter"]

[build]
publication = "vyasa:minimal:default"
layout = "document"
templates = ["html"]
target = "view"
output = "minimal.vyview"
