[workspace]
name = "bible"
title = "Bible Sample"
source = "https://www.bible.com/bible/111/JHN.14.NIV"
path_schema = []
publisher = "../../"

[urn]
corpus = "john"
hierarchy = ["chapter"]
bit_layout = [16]

[build.default]
layout = "document"
target = "view"
output_dir = "build"
