[workspace]
name = "Bible Sample"
source = "https://www.bible.com/bible/111/JHN.14.NIV"
path_schema = []

[urn]
publisher = "bible.com"
corpus = "john"
hierarchy = ["chapter"]

[build]
publication = "bible.com:JHN.14:default"
layout = "document"
templates = ["html"]
target = "view"
output = "bible.vyview"
