[workspace]
name = "bible"
title = "Bible Sample"
[publish]
publisher_dir = "../../"

[urn]
path_schema = ["chapter"]
corpus = "john"
hierarchy = ["chapter"]
bit_layout = [16]

[build.default]
layout = "document"
