[workspace]
name = "Bhagavad Gita"
description = "Bhagavad Gita with Devanagari and IAST streams."
path_schema = ["chapter"]

[urn]
publisher = "vyasa.io"
corpus = "bg"
hierarchy = ["chapter", "verse"]

[build]
publication = "vyasa.org:bg:default"
layout = "sequence"
templates = ["html"]
target = "view"
output = "vyasa-bg.vyview"
