[workspace]
name = "vedabase-bg"
id = "vedabase-bg"
title = "Bhagavad Gita (Vedabase)"

[publish]
publisher_dir = "../../"

[urn]
path_schema = ["chapter", "verse"]
hierarchy = ["chapter", "verse"]

[build.default]
enable_markdown = true
layout = "document"
target = "view"
[dependencies]
base_corpus = { package = "vyasa-bg" }

[streams]
mula = { path = "content/mula" }
iast = { path = "content/iast" }
translation = { path = "content/translation" }
